### ISSUE TITLE
Update project to support modern Ubuntu versions (18.04 and newer)

### ISSUE THREAD

**Issue by desrod** [SecretAgentKen/deckxstream#8]
Currently, this does not build cleanly with all correct dependencies on a clean 18.04, 20.04 nor 22.04 Ubuntu release version. 

I'm not an expert in node.js, but it shouldn't be a huge uplift to test and verify that it should work on those environments, and make any dependency version adjustments needed to get it working there. 

Oh, and screenshots of the UI on this project's main page would be great!

**Comment by SecretAgentKen** [comment]
It builds fine on 22 which is ubuntu-latest in GitHub on Node 14, 16, and 18 which is part of its automated workflow and I just reran it to confirm. 

If you are not an expert, please do not specify what shouldn't be a huge lift, especially if you don't provide any details regarding what doesn't build. All compiled portions of this are from third-party libraries. 

As for screenshots, this is a headless server entirely configured by a JSON file. There's nothing to screenshot.
